server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sell_phone_app_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
